import cron from 'node-cron';
import prisma from '../config/prisma';
import redis from '../config/redis';
import logger from '../config/logger';
import { sendPush } from '../services/notification.service';
import { generateLoveReason } from '../services/loveReasonGenerator';

/**
 * LoveBot Cron Job
 *
 * Runs every minute. For each active couple with lovebotMode !== "off":
 * - Checks if the current time (HH:MM IST) matches lovebotTime
 * - Uses Redis dedup key to prevent double-sends per day
 * - Picks an unused love reason, marks it used, sends push notification
 *
 * Observability — every meaningful state transition is logged with a stable
 * structured shape so log queries can answer "did couple X get delivered
 * today, and if not why?" in one pass. Keys we always include where relevant:
 *   { coupleId, senderId, recipientId, dateKey, reasonId, autoGenerated,
 *     dedupState, pushStatus, durationMs }
 *
 * Reliability — on server boot we also run a catch-up scan over the last few
 * minutes. If a delivery was scheduled while the dyno was restarting (deploy
 * crossed the firing minute on Render free tier), we still deliver it as soon
 * as the process is alive. Without this the system silently skipped any
 * minute where a deploy happened to land on a user's scheduled time.
 */

// How many minutes back to scan for missed deliveries when the server boots.
// 5 covers any normal Render restart window comfortably (cold-start +
// deploy + warm-up + buffer). Anything older than that is too stale to
// surprise-deliver — we'd rather wait for tomorrow's normal slot than send a
// note at the "wrong" time relative to what the user configured.
const CATCH_UP_WINDOW_MINUTES = 5;

export const startLoveBotCron = (): void => {
  cron.schedule('* * * * *', async () => {
    await runOnce({ source: 'tick' });
  });

  logger.info('[LoveBot] Cron job started (every minute)');

  // Fire a catch-up sweep right after boot. Using setImmediate (instead of
  // awaiting here) keeps startup non-blocking — the rest of the server can
  // come online while we backfill any missed deliveries asynchronously.
  setImmediate(async () => {
    try {
      await catchUp();
    } catch (err: any) {
      logger.error({ err: err.message }, '[LoveBot] Catch-up failed');
    }
  });
};

/**
 * One scheduler "tick" — figure out which couples (if any) are due for a
 * delivery right now and process each in sequence. Extracted from the
 * cron.schedule callback so the catch-up path can reuse the same logic.
 */
async function runOnce({ source, overrideTime }: { source: 'tick' | 'catchup'; overrideTime?: { time: string; dateKey: string } }): Promise<void> {
  const start = Date.now();
  try {
    let currentTime: string;
    let todayKey: string;

    if (overrideTime) {
      currentTime = overrideTime.time;
      todayKey = overrideTime.dateKey;
    } else {
      const now = istNow();
      currentTime = `${String(now.getUTCHours()).padStart(2, '0')}:${String(now.getUTCMinutes()).padStart(2, '0')}`;
      todayKey = now.toISOString().split('T')[0];
    }

    const couples = await prisma.couple.findMany({
      where: {
        status: 'active',
        userBId: { not: null },
        OR: [
          { userALoveBotMode: { not: 'off' }, userALoveBotTime: currentTime },
          { userBAccessGranted: true, userBLoveBotMode: { not: 'off' }, userBLoveBotTime: currentTime },
        ],
      },
      select: {
        id: true,
        userAId: true,
        userBId: true,
        userALoveBotMode: true,
        userALoveBotTime: true,
        userBAccessGranted: true,
        userBLoveBotMode: true,
        userBLoveBotTime: true,
      },
    });

    if (couples.length === 0) {
      // Tick-level logs are noisy at debug — only the catch-up path explicitly
      // logs a "0 couples" outcome so an admin can verify the boot sweep ran.
      if (source === 'catchup') {
        logger.info({ source, currentTime, dateKey: todayKey, matched: 0 }, '[LoveBot] No deliveries due');
      }
      return;
    }

    logger.info(
      { source, currentTime, dateKey: todayKey, matched: couples.length },
      '[LoveBot] Tick — couples due'
    );

    for (const couple of couples) {
      // User A's bot → user B
      if (couple.userALoveBotMode !== 'off' && couple.userALoveBotTime === currentTime) {
        await processUserCronRule({
          coupleId: couple.id,
          senderId: couple.userAId,
          recipientId: couple.userBId!,
          mode: couple.userALoveBotMode,
          dateKey: todayKey,
          source,
        });
      }
      // User B's bot → user A
      if (
        couple.userBAccessGranted &&
        couple.userBLoveBotMode !== 'off' &&
        couple.userBLoveBotTime === currentTime
      ) {
        await processUserCronRule({
          coupleId: couple.id,
          senderId: couple.userBId!,
          recipientId: couple.userAId,
          mode: couple.userBLoveBotMode,
          dateKey: todayKey,
          source,
        });
      }
    }
  } catch (err: any) {
    logger.error({ err: err.message, source }, '[LoveBot] Tick error');
  } finally {
    const durationMs = Date.now() - start;
    if (durationMs > 5000) {
      // Surface slow ticks so we notice if Gemini latency or DB backpressure
      // start dragging individual cron runs past the next minute boundary.
      logger.warn({ durationMs, source }, '[LoveBot] Slow tick');
    }
  }
}

/**
 * Backfill any deliveries that should have happened in the last
 * CATCH_UP_WINDOW_MINUTES minutes but weren't recorded as sent. Used on boot
 * to recover from deploy / cold-start windows on Render's free tier.
 *
 * The dedup key check inside processUserCronRule makes this idempotent — any
 * minute that already delivered (or already failed for the day) will short-
 * circuit on its existing Redis key. The catch-up only does work for minutes
 * that genuinely missed.
 */
async function catchUp(): Promise<void> {
  const now = istNow();
  // Start from the most recent minute and walk backward; that way if a couple
  // had multiple eligible minutes in the window we still only deliver the
  // first one we encounter and the dedup key blocks the older ones.
  for (let i = 0; i <= CATCH_UP_WINDOW_MINUTES; i++) {
    const t = new Date(now.getTime() - i * 60 * 1000);
    const time = `${String(t.getUTCHours()).padStart(2, '0')}:${String(t.getUTCMinutes()).padStart(2, '0')}`;
    const dateKey = t.toISOString().split('T')[0];
    await runOnce({ source: 'catchup', overrideTime: { time, dateKey } });
  }
  logger.info({ windowMinutes: CATCH_UP_WINDOW_MINUTES }, '[LoveBot] Boot catch-up complete');
}

interface CronRuleInput {
  coupleId: string;
  senderId: string;
  recipientId: string;
  mode: string;
  dateKey: string;
  source: 'tick' | 'catchup';
}

async function processUserCronRule(input: CronRuleInput): Promise<void> {
  const { coupleId, senderId, recipientId, mode, dateKey, source } = input;
  const dedupKey = `lovebot:sent:${coupleId}:${senderId}:${dateKey}`;
  const logCtx = { coupleId, senderId, recipientId, dateKey, source };

  const alreadySent = await redis.get(dedupKey);
  if (alreadySent) {
    // Catch-up frequently hits this — that's the whole point of dedup. Keep
    // it at debug so tick-time logs aren't drowned by per-minute "already
    // sent" lines, but expose the state value so we can grep for stuck
    // 'failed' rows from the previous day if a couple stops receiving.
    logger.debug({ ...logCtx, dedupState: alreadySent }, '[LoveBot] Dedup hit — skipping');
    return;
  }

  if (mode === 'surprise' && Math.random() > 0.5) {
    await redis.set(dedupKey, 'skipped', 'EX', 86400);
    logger.info({ ...logCtx }, '[LoveBot] Surprise mode coin flip — skipped today');
    return;
  }

  // Existing behavior: user-authored reasons win when available. Picking the
  // oldest unused row first means manually-added reasons get exhausted before
  // we start auto-generating, which matches the user's mental model ("I wrote
  // these specifically for them").
  let reason = await prisma.loveReason.findFirst({
    where: { coupleId, forUserId: recipientId, used: false },
    orderBy: { createdAt: 'asc' },
  });

  let autoGenerated = false;

  if (!reason) {
    const [sender, recipient, recent] = await Promise.all([
      prisma.user.findUnique({ where: { id: senderId }, select: { name: true } }),
      prisma.user.findUnique({ where: { id: recipientId }, select: { name: true } }),
      prisma.loveReason.findMany({
        where: { coupleId, forUserId: recipientId, used: true },
        orderBy: { deliveredAt: 'desc' },
        take: 10,
        select: { reason: true },
      }),
    ]);

    if (!sender || !recipient) {
      logger.warn({ ...logCtx }, '[LoveBot] Missing user record(s), skipping auto-gen');
      // Set dedup anyway so we don't retry every minute for the rest of the day.
      await redis.set(dedupKey, 'skipped-missing-user', 'EX', 86400);
      return;
    }

    try {
      const generated = await generateLoveReason({
        senderName: sender.name,
        recipientName: recipient.name,
        recentReasons: recent.map((r) => r.reason),
      });

      reason = await prisma.loveReason.create({
        data: {
          coupleId,
          authorId: senderId,
          forUserId: recipientId,
          reason: generated,
          used: false,
        },
      });
      autoGenerated = true;
    } catch (err: any) {
      logger.error({ ...logCtx, err: err.message }, '[LoveBot] Auto-gen insert failed');
      // Short TTL on failure so a transient Gemini / Prisma blip doesn't lock
      // the couple out for the rest of the day — the next minute's tick can
      // retry. 5 minutes is enough to clear most transient outages without
      // hammering an actually-down service.
      await redis.set(dedupKey, 'failed', 'EX', 300);
      return;
    }
  }

  await prisma.loveReason.update({
    where: { id: reason.id },
    data: { used: true, deliveredAt: new Date() },
  });

  const sender = await prisma.user.findUnique({ where: { id: senderId }, select: { name: true } });

  const pushResult = await sendPush(
    recipientId,
    '💌 Love Note Delivered',
    `You have a new message from ${sender?.name} 💌`,
    { type: 'lovebot', url: '/home' }
  );

  logger.info(
    {
      ...logCtx,
      reasonId: reason.id,
      autoGenerated,
      pushStatus: pushResult.status,
      ...(pushResult.status === 'skipped' && { pushSkipReason: pushResult.reason }),
      ...(pushResult.status === 'failed' && { pushError: pushResult.error }),
    },
    '[LoveBot] Reason sent'
  );

  await redis.set(dedupKey, 'sent', 'EX', 86400);
}

/**
 * Returns the current UTC instant shifted by IST's +5:30 offset, so that
 * reading getUTCHours/getUTCMinutes on the result gives IST clock time. This
 * matches how user-configured lovebotTime strings (e.g. "09:00") are stored
 * and what the home-screen settings UI displays.
 */
function istNow(): Date {
  return new Date(Date.now() + 5.5 * 60 * 60 * 1000);
}
