import cron from 'node-cron';
import prisma from '../config/prisma';
import redis from '../config/redis';
import logger from '../config/logger';
import { sendPush } from '../services/notification.service';
import { generateLoveReason } from '../services/loveReasonGenerator';

/**
 * LoveBot Cron Job
 * Runs every minute. For each active couple with lovebotMode !== "off":
 * - Checks if the current time (HH:MM UTC) matches lovebotTime
 * - Uses Redis dedup key to prevent double-sends per day
 * - Picks an unused love reason, marks it used, sends push notification
 * - Respects lovebotTarget: "both" or "partner_only"
 */
export const startLoveBotCron = (): void => {
  cron.schedule('* * * * *', async () => {
    try {
      // Force India Standard Time (IST) offset for correct matching with user inputs
      const utcTime = new Date();
      const now = new Date(utcTime.getTime() + (5.5 * 60 * 60 * 1000));
      
      const currentTime = `${String(now.getUTCHours()).padStart(2, '0')}:${String(now.getUTCMinutes()).padStart(2, '0')}`;
      const todayKey = now.toISOString().split('T')[0]; // YYYY-MM-DD

      // Find active couples
      const couples = await prisma.couple.findMany({
        where: {
          status: 'active',
          userBId: { not: null },
          OR: [
            { userALoveBotMode: { not: 'off' }, userALoveBotTime: currentTime },
            { userBAccessGranted: true, userBLoveBotMode: { not: 'off' }, userBLoveBotTime: currentTime }
          ]
        },
        select: {
          id: true,
          userAId: true,
          userBId: true,
          userALoveBotMode: true,
          userALoveBotTime: true,
          userBAccessGranted: true,
          userBLoveBotMode: true,
          userBLoveBotTime: true,
        },
      });

      for (const couple of couples) {
        // --- Process User A -> User B ---
        if (couple.userALoveBotMode !== 'off' && couple.userALoveBotTime === currentTime) {
          await processUserCronRule(
            couple.id,
            couple.userAId,
            couple.userBId!, 
            couple.userALoveBotMode, 
            todayKey
          );
        }

        // --- Process User B -> User A ---
        if (couple.userBAccessGranted && couple.userBLoveBotMode !== 'off' && couple.userBLoveBotTime === currentTime) {
          await processUserCronRule(
            couple.id,
            couple.userBId!,
            couple.userAId, 
            couple.userBLoveBotMode, 
            todayKey
          );
        }
      }
    } catch (err: any) {
      logger.error({ err: err.message }, '[LoveBot] Cron error');
    }
  });

  logger.info('[LoveBot] Cron job started (every minute)');
};

async function processUserCronRule(coupleId: string, senderId: string, recipientId: string, mode: string, dateKey: string) {
  const dedupKey = `lovebot:sent:${coupleId}:${senderId}:${dateKey}`;

  const alreadySent = await redis.get(dedupKey);
  if (alreadySent) return;

  if (mode === 'surprise' && Math.random() > 0.5) {
    await redis.set(dedupKey, 'skipped', 'EX', 86400);
    return;
  }

  // Existing behavior: user-authored reasons win when available. Picking the
  // oldest unused row first means manually-added reasons get exhausted before
  // we start auto-generating, which matches the user's mental model ("I wrote
  // these specifically for them").
  let reason = await prisma.loveReason.findFirst({
    where: { coupleId, forUserId: recipientId, used: false },
    orderBy: { createdAt: 'asc' },
  });

  let autoGenerated = false;

  // Fallback: no user-authored reason available → generate one via Gemini and
  // insert as a system-authored row. authorId is set to the *sender* so the
  // semantics still make sense ("delivered on senderId's behalf") and the FK
  // doesn't need to allow null. The row goes through the same `used: true` +
  // `deliveredAt` update path below as any user-authored reason would.
  if (!reason) {
    const [sender, recipient, recent] = await Promise.all([
      prisma.user.findUnique({ where: { id: senderId }, select: { name: true } }),
      prisma.user.findUnique({ where: { id: recipientId }, select: { name: true } }),
      prisma.loveReason.findMany({
        where: { coupleId, forUserId: recipientId, used: true },
        orderBy: { deliveredAt: 'desc' },
        take: 10,
        select: { reason: true },
      }),
    ]);

    if (!sender || !recipient) {
      logger.warn({ coupleId, senderId, recipientId }, '[LoveBot] Missing user record(s), skipping auto-gen');
      // Set dedup anyway so we don't retry every minute for the rest of the day.
      await redis.set(dedupKey, 'skipped-missing-user', 'EX', 86400);
      return;
    }

    try {
      const generated = await generateLoveReason({
        senderName: sender.name,
        recipientName: recipient.name,
        recentReasons: recent.map((r) => r.reason),
      });

      reason = await prisma.loveReason.create({
        data: {
          coupleId,
          authorId: senderId,
          forUserId: recipientId,
          reason: generated,
          used: false,
        },
      });
      autoGenerated = true;
    } catch (err: any) {
      // generateLoveReason already handles Gemini failures internally (returns
      // a fallback). If we got here it's a Prisma error inserting the row,
      // which is genuinely unexpected — log and skip for today.
      logger.error({ err: err.message, coupleId }, '[LoveBot] Auto-gen insert failed');
      await redis.set(dedupKey, 'failed', 'EX', 86400);
      return;
    }
  }

  await prisma.loveReason.update({
    where: { id: reason.id },
    data: { used: true, deliveredAt: new Date() },
  });

  const sender = await prisma.user.findUnique({ where: { id: senderId }, select: { name: true } });

  await sendPush(
    recipientId,
    '💌 Love Note Delivered',
    `You have a new message from ${sender?.name} 💌`,
    { type: 'lovebot', url: '/home' }
  );

  logger.info(
    { coupleId, recipientId, reasonId: reason.id, autoGenerated },
    '[LoveBot] Reason sent'
  );

  await redis.set(dedupKey, 'sent', 'EX', 86400);
}

